import{storageMode,signIn,listProducts,saveProduct,deleteProduct,uploadProductImage}from"./data-service.js?v=2";

const $=selector=>document.querySelector(selector);
const loginScreen=$("#login-screen"),managerApp=$("#manager-app"),form=$("#product-form"),drawer=$("#product-drawer"),backdrop=$("#drawer-backdrop");
let session=null,products=[],filterPlatform="Semua",pendingDelete=null,imageMode="upload",currentImage="";
const escapeHtml=(value="")=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);

function toast(message){const item=$("#toast");item.textContent=message;item.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>item.classList.remove("show"),2600);}
function token(){return session?.access_token||"";}
function showApp(){loginScreen.classList.add("hidden");managerApp.classList.remove("hidden");$("#manager-email").textContent=session?.user?.email||session?.email||"Viral Picks MY";$("#demo-banner").classList.toggle("hidden",storageMode!=="demo");loadProducts();}
function openDrawer(product=null){form.reset();$("#product-id").value=product?.id||"";$("#product-name").value=product?.name||"";$("#product-platform").value=product?.platform||"Shopee";$("#product-category").value=product?.category||"";$("#product-link").value=product?.affiliate_url||"";$("#product-active").checked=product?.active??true;$("#drawer-title").textContent=product?"Edit barang":"Tambah barang";currentImage=product?.image_url||"";setImageMode("upload");renderPreview();drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");backdrop.classList.remove("hidden");setTimeout(()=>$("#product-name").focus(),100);}
function closeDrawer(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");backdrop.classList.add("hidden");}
function setImageMode(mode){imageMode=mode;document.querySelectorAll("[data-image-mode]").forEach(button=>button.classList.toggle("active",button.dataset.imageMode===mode));$("#upload-zone").classList.toggle("hidden",mode!=="upload");$("#image-url-field").classList.toggle("hidden",mode!=="url");}
function renderPreview(){const preview=$("#image-preview");preview.classList.toggle("hidden",!currentImage);if(currentImage)preview.querySelector("img").src=currentImage;}
function platformMark(value){return value==="Shopee"?'<span class="platform-dot shopee">S</span>':'<span class="platform-dot tiktok">♪</span>';}
function visibleProducts(){const term=$("#manager-search").value.trim().toLowerCase();return products.filter(item=>(filterPlatform==="Semua"||item.platform===filterPlatform)&&(!term||`${item.name} ${item.category}`.toLowerCase().includes(term)));}
function renderList(){const items=visibleProducts();$("#manager-count").textContent=products.length;$("#manager-empty").classList.toggle("hidden",items.length>0);$("#manager-list").innerHTML=items.map(item=>`<div class="manager-row" data-id="${escapeHtml(item.id)}"><div class="manager-product">${item.image_url?`<img src="${escapeHtml(item.image_url)}" alt="" referrerpolicy="no-referrer">`:'<div class="no-image">▧</div>'}<div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.affiliate_url)}</small></div></div><span class="table-platform">${platformMark(item.platform)}${escapeHtml(item.platform)}</span><span>${escapeHtml(item.category)}</span><span class="status-chip ${item.active?"":"hidden-status"}">${item.active?"Aktif":"Sorok"}</span><div class="row-actions"><button data-action="edit">Edit</button><button data-action="toggle">${item.active?"Sorok":"Papar"}</button><button data-action="up" title="Naikkan susunan">↑</button><button data-action="down" title="Turunkan susunan">↓</button><button class="delete" data-action="delete">Buang</button></div></div>`).join("");
  document.querySelectorAll(".manager-row").forEach(row=>row.onclick=async event=>{const button=event.target.closest("button[data-action]");if(!button)return;const item=products.find(value=>String(value.id)===row.dataset.id);if(!item)return;const action=button.dataset.action;if(action==="edit")openDrawer(item);if(action==="delete"){pendingDelete=item;$("#confirm-modal").classList.remove("hidden");}if(action==="toggle"){await saveProduct({...item,active:!item.active},token());await loadProducts();toast(item.active?"Barang disorok":"Barang dipaparkan");}if(action==="up"||action==="down")await moveItem(item,action==="up"?-1:1);});
}
async function loadProducts(){try{products=await listProducts({includeHidden:true});renderList();}catch(error){toast(error.message);}}
async function moveItem(item,direction){const index=products.findIndex(value=>value.id===item.id),target=products[index+direction];if(!target)return;const original=item.position;await saveProduct({...item,position:target.position},token());await saveProduct({...target,position:original},token());await loadProducts();toast("Susunan dikemas kini");}

$("#login-form").onsubmit=async event=>{event.preventDefault();$("#login-note").textContent="";try{session=await signIn($("#login-email").value,$("#login-password").value);if(session.access_token)sessionStorage.setItem("viral-picks-session",JSON.stringify(session));showApp();}catch(error){$("#login-note").textContent=error.message;}};
if(storageMode==="demo"){$("#login-form").classList.add("hidden");$("#demo-entry").classList.remove("hidden");$("#login-note").textContent="Storan online belum diaktifkan. Gunakan pratonton untuk cuba fungsi Manager.";$("#demo-entry").onclick=()=>{session={demo:true,email:"Pratonton setempat"};showApp();};}
else{try{session=JSON.parse(sessionStorage.getItem("viral-picks-session"));if(session?.access_token)showApp();}catch{session=null;}}
$("#logout-button").onclick=()=>{sessionStorage.removeItem("viral-picks-session");location.reload();};
$("#add-product").onclick=()=>openDrawer();$("#close-drawer").onclick=closeDrawer;$("#cancel-product").onclick=closeDrawer;backdrop.onclick=closeDrawer;
document.querySelectorAll("[data-image-mode]").forEach(button=>button.onclick=()=>setImageMode(button.dataset.imageMode));
$("#product-file").onchange=async event=>{const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){toast("Gambar melebihi 5MB");event.target.value="";return;}currentImage=URL.createObjectURL(file);renderPreview();};
$("#product-image-url").oninput=event=>{currentImage=event.target.value.trim();renderPreview();};
$("#remove-image").onclick=()=>{currentImage="";$("#product-file").value="";$("#product-image-url").value="";renderPreview();};
form.onsubmit=async event=>{event.preventDefault();const saveButton=$("#save-product");saveButton.disabled=true;saveButton.textContent="Menyimpan...";try{const existing=products.find(item=>String(item.id)===$("#product-id").value);let imageUrl=currentImage;if(imageMode==="upload"&&$("#product-file").files[0])imageUrl=await uploadProductImage($("#product-file").files[0],token());if(imageMode==="url")imageUrl=$("#product-image-url").value.trim();await saveProduct({id:existing?.id,name:$("#product-name").value.trim(),platform:$("#product-platform").value,category:$("#product-category").value.trim(),affiliate_url:$("#product-link").value.trim(),image_url:imageUrl,active:$("#product-active").checked,position:existing?.position||products.length+1},token());closeDrawer();await loadProducts();toast(existing?"Barang berjaya dikemas kini":"Barang berjaya ditambah");}catch(error){toast(error.message);}finally{saveButton.disabled=false;saveButton.textContent="Simpan barang";}};
$("#manager-search").oninput=renderList;document.querySelectorAll("#manager-tabs button").forEach(button=>button.onclick=()=>{filterPlatform=button.dataset.platform;document.querySelectorAll("#manager-tabs button").forEach(item=>item.classList.toggle("active",item===button));renderList();});
$("#cancel-delete").onclick=()=>{$("#confirm-modal").classList.add("hidden");pendingDelete=null;};
$("#confirm-delete").onclick=async()=>{if(!pendingDelete)return;try{await deleteProduct(pendingDelete.id,token());$("#confirm-modal").classList.add("hidden");pendingDelete=null;await loadProducts();toast("Barang sudah dibuang");}catch(error){toast(error.message);}};
