import{storageMode,signIn,listProducts,saveProduct,deleteProduct,uploadProductImage}from"./data-service.js?v=2";

const $=selector=>document.querySelector(selector);
const loginScreen=$("#login-screen"),managerApp=$("#manager-app"),form=$("#product-form"),drawer=$("#product-drawer"),backdrop=$("#drawer-backdrop");
let session=null,products=[],filterPlatform="Semua",pendingDelete=null,imageMode="upload",currentImage="";
const escapeHtml=(value="")=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);

function toast(message){const item=$("#toast");item.textContent=message;item.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>item.classList.remove("show"),2600);}
function token(){return session?.access_token||"";}
function showApp(){loginScreen.classList.add("hidden");managerApp.classList.remove("hidden");$("#manager-email").textContent=session?.user?.email||session?.email||"Viral Picks MY";$("#demo-banner").classList.toggle("hidden",storageMode!=="demo");loadProducts();}
function setDetailsVisible(show){$("#autofill-details").classList.toggle("hidden",!show);$("#manual-details-toggle").textContent=show?"Sembunyikan maklumat produk":"Lihat / ubah maklumat produk";}
function setFetchStatus(message,state=""){$("#fetch-status").textContent=message;$("#fetch-status").dataset.state=state;}
function openDrawer(product=null){form.reset();$("#product-id").value=product?.id||"";$("#product-name").value=product?.name||"";$("#product-platform").value=product?.platform||"Shopee";$("#product-category").value=product?.category||"";$("#product-link").value=product?.affiliate_url||"";$("#product-active").checked=product?.active??true;$("#drawer-title").textContent=product?"Edit barang":"Tambah barang";$("#drawer-subtitle").textContent=product?"Ubah maklumat yang diperlukan.":"Tampal link sahaja. Sistem akan cuba isi selebihnya.";currentImage=product?.image_url||"";setImageMode(currentImage?"url":"upload");$("#product-image-url").value=currentImage;renderPreview();setDetailsVisible(Boolean(product));setFetchStatus(product?"Maklumat produk sedia untuk diubah.":"Nama, gambar, platform dan kategori akan diisi secara automatik.");drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");backdrop.classList.remove("hidden");setTimeout(()=>$("#product-link").focus(),100);}
function closeDrawer(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");backdrop.classList.add("hidden");}
function setImageMode(mode){imageMode=mode;document.querySelectorAll("[data-image-mode]").forEach(button=>button.classList.toggle("active",button.dataset.imageMode===mode));$("#upload-zone").classList.toggle("hidden",mode!=="upload");$("#image-url-field").classList.toggle("hidden",mode!=="url");}
function renderPreview(){const preview=$("#image-preview");preview.classList.toggle("hidden",!currentImage);if(currentImage)preview.querySelector("img").src=currentImage;}
function platformMark(value){return value==="Shopee"?'<span class="platform-dot shopee">S</span>':'<span class="platform-dot tiktok">♪</span>';}
function cleanProductName(value=""){return String(value).replace(/\s*Catatan:.*$/i,"").trim();}
function managerImage(item){return item.image_url||window.legacyProductImages?.[item.affiliate_url]||"";}
function normalizeProductUrl(value){const raw=String(value||"").trim();if(!raw)throw new Error("Tampal link produk dahulu");const url=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!/shopee|tiktok/i.test(url.hostname))throw new Error("Gunakan link produk Shopee atau TikTok");return url;}
function detectPlatform(url){return /shopee/i.test(url.hostname)?"Shopee":"TikTok Shop";}
function embeddedMetadata(url){try{const value=url.searchParams.get("og_info");if(!value)return {};const info=JSON.parse(value);return {title:info.title||"",image:info.image||""};}catch{return {};}}
function titleFromUrl(url,platform){if(platform!=="Shopee")return "";let slug=decodeURIComponent(url.pathname.split("/").filter(Boolean).pop()||"");slug=slug.replace(/-i\.\d+\.\d+.*$/i,"").replace(/\.\d+\.\d+.*$/,"").replace(/[-_]+/g," ").replace(/\s+/g," ").trim();return slug.length>5?slug:"";}
function inferCategory(name){const value=String(name||"").toLowerCase();const groups=[
  ["Perfume & Wangian Peribadi",["perfume","parfum","wangian","fragrance","eau de"]],
  ["Suplemen & Kesihatan",["supplement","suplemen","vitamin","probiotic","omega","tablet","gummies","kesihatan","collagen"]],
  ["Makanan & Minuman",["kopi","coffee","sambal","makanan","minuman","coklat","chocolate","cookies","kicap","sos","spread","kurma","kek","snack"]],
  ["Beauty, Skincare & Penjagaan Diri",["skincare","serum","lotion","beauty","makeup","cream","syampu","shampoo","sabun"]],
  ["Home & Living",["vacuum","iron","dapur","rumah","cleaner","mop","air fryer"]],
  ["Automotif",["kereta","car ","automotive","motosikal","motorcycle","wiper"]],
  ["Fashion, Outdoor & Aksesori",["baju","shirt","dress","umbrella","payung","raincoat","kasut","shoe","fashion"]],
  ["Elektronik, Kipas & Gadget",["power bank","powerbank","charger","earbuds","speaker","gadget","kipas","fan","usb"]],
  ["Beg & Aksesori Wanita",["beg tangan","handbag","tote","crossbody","shoulder bag"]]
];return groups.find(([,words])=>words.some(word=>value.includes(word)))?.[0]||"Lain-lain";}
async function fetchJson(url,timeout=14000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw new Error("Maklumat tidak ditemui");return await response.json();}finally{clearTimeout(timer);}}
async function lookupProduct(rawUrl){const url=normalizeProductUrl(rawUrl),platform=detectPlatform(url),embedded=embeddedMetadata(url);let title=embedded.title||titleFromUrl(url,platform),image=embedded.image||"";
  if(!title&&platform==="TikTok Shop"&&!/vt\.tiktok\.com/i.test(url.hostname)){try{const data=await fetchJson(`https://www.tiktok.com/oembed?url=${encodeURIComponent(url.href)}`,9000);title=data.title||"";image=image||data.thumbnail_url||"";}catch{}}
  if(!title||!image){try{const cleanUrl=new URL(url.href);if(embedded.title)cleanUrl.search="";const data=await fetchJson(`https://api.microlink.io/?url=${encodeURIComponent(cleanUrl.href)}`,8000);if(data.status==="success"){const remoteTitle=data.data?.title||"",generic=/shopee malaysia|free shipping across|make your day/i.test(remoteTitle);if(!generic){title=title||remoteTitle;image=image||data.data?.image?.url||"";}}}catch{}}
  title=cleanProductName(title||titleFromUrl(url,platform));if(!title)throw new Error("Link pendek ini tidak beri nama produk. Guna link penuh daripada halaman produk.");return {title,image,platform,category:inferCategory(title)};
}
async function autofillProduct(){const button=$("#fetch-product"),link=$("#product-link").value.trim();button.disabled=true;button.textContent="Sedang mencari...";setFetchStatus("Sistem sedang membaca maklumat produk...","loading");try{const data=await lookupProduct(link);$("#product-name").value=data.title;$("#product-platform").value=data.platform;$("#product-category").value=data.category;currentImage=data.image||"";$("#product-image-url").value=currentImage;if(currentImage)setImageMode("url");renderPreview();setDetailsVisible(true);setFetchStatus(currentImage?"Siap! Nama, gambar, platform dan kategori berjaya diisi.":"Nama, platform dan kategori berjaya diisi. Gambar tidak dibenarkan oleh platform; abg masih boleh simpan.",currentImage?"success":"partial");return true;}catch(error){setDetailsVisible(true);setFetchStatus(error.message,"error");return false;}finally{button.disabled=false;button.textContent="Cari maklumat automatik";}}
function visibleProducts(){const term=$("#manager-search").value.trim().toLowerCase();return products.filter(item=>(filterPlatform==="Semua"||item.platform===filterPlatform)&&(!term||`${item.name} ${item.category}`.toLowerCase().includes(term)));}
function renderList(){const items=visibleProducts();$("#manager-count").textContent=products.length;$("#manager-empty").classList.toggle("hidden",items.length>0);$("#manager-list").innerHTML=items.map(item=>{const image=managerImage(item),name=cleanProductName(item.name);return `<div class="manager-row" data-id="${escapeHtml(item.id)}"><div class="manager-product">${image?`<img src="${escapeHtml(image)}" alt="Gambar ${escapeHtml(name)}" loading="lazy" referrerpolicy="no-referrer">`:'<div class="no-image">VP</div>'}<div class="manager-product-copy"><strong title="${escapeHtml(name)}">${escapeHtml(name)}</strong><small title="${escapeHtml(item.affiliate_url)}">${escapeHtml(item.affiliate_url)}</small></div></div><span class="table-platform">${platformMark(item.platform)}${escapeHtml(item.platform)}</span><span class="manager-category">${escapeHtml(item.category)}</span><span class="status-chip ${item.active?"":"hidden-status"}">${item.active?"Aktif":"Sorok"}</span><div class="row-actions"><button data-action="edit">Edit</button><button class="toggle" data-action="toggle">${item.active?"Sorok":"Papar"}</button><button data-action="up" title="Naikkan susunan" aria-label="Naikkan susunan">↑ <span>Naik</span></button><button data-action="down" title="Turunkan susunan" aria-label="Turunkan susunan">↓ <span>Turun</span></button><button class="delete" data-action="delete">Buang</button></div></div>`;}).join("");
  document.querySelectorAll(".manager-product img").forEach(img=>img.addEventListener("error",()=>{const fallback=document.createElement("div");fallback.className="no-image";fallback.textContent="VP";img.replaceWith(fallback);},{once:true}));
  document.querySelectorAll(".manager-row").forEach(row=>row.onclick=async event=>{const button=event.target.closest("button[data-action]");if(!button)return;const item=products.find(value=>String(value.id)===row.dataset.id);if(!item)return;const action=button.dataset.action;if(action==="edit")openDrawer(item);if(action==="delete"){pendingDelete=item;$("#confirm-modal").classList.remove("hidden");}if(action==="toggle"){await saveProduct({...item,active:!item.active},token());await loadProducts();toast(item.active?"Barang disorok":"Barang dipaparkan");}if(action==="up"||action==="down")await moveItem(item,action==="up"?-1:1);});
}
async function loadProducts(){try{products=await listProducts({includeHidden:true});renderList();}catch(error){toast(error.message);}}
async function moveItem(item,direction){const index=products.findIndex(value=>value.id===item.id),target=products[index+direction];if(!target)return;const original=item.position;await saveProduct({...item,position:target.position},token());await saveProduct({...target,position:original},token());await loadProducts();toast("Susunan dikemas kini");}

$("#login-form").onsubmit=async event=>{event.preventDefault();$("#login-note").textContent="";try{session=await signIn($("#login-email").value,$("#login-password").value);if(session.access_token)sessionStorage.setItem("viral-picks-session",JSON.stringify(session));showApp();}catch(error){$("#login-note").textContent=error.message;}};
if(storageMode==="demo"){$("#login-form").classList.add("hidden");$("#demo-entry").classList.remove("hidden");$("#login-note").textContent="Storan online belum diaktifkan. Gunakan pratonton untuk cuba fungsi Manager.";$("#demo-entry").onclick=()=>{session={demo:true,email:"Pratonton setempat"};showApp();};}
else{try{session=JSON.parse(sessionStorage.getItem("viral-picks-session"));if(session?.access_token)showApp();}catch{session=null;}}
$("#logout-button").onclick=()=>{sessionStorage.removeItem("viral-picks-session");location.reload();};
$("#add-product").onclick=()=>openDrawer();$("#close-drawer").onclick=closeDrawer;$("#cancel-product").onclick=closeDrawer;backdrop.onclick=closeDrawer;
$("#manual-details-toggle").onclick=()=>setDetailsVisible($("#autofill-details").classList.contains("hidden"));
$("#fetch-product").onclick=autofillProduct;
$("#product-link").addEventListener("paste",()=>setTimeout(()=>autofillProduct(),80));
document.querySelectorAll("[data-image-mode]").forEach(button=>button.onclick=()=>setImageMode(button.dataset.imageMode));
$("#product-file").onchange=async event=>{const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){toast("Gambar melebihi 5MB");event.target.value="";return;}currentImage=URL.createObjectURL(file);renderPreview();};
$("#product-image-url").oninput=event=>{currentImage=event.target.value.trim();renderPreview();};
$("#remove-image").onclick=()=>{currentImage="";$("#product-file").value="";$("#product-image-url").value="";renderPreview();};
form.onsubmit=async event=>{event.preventDefault();const saveButton=$("#save-product"),existing=products.find(item=>String(item.id)===$("#product-id").value);if(!$("#product-link").value.trim()){setFetchStatus("Tampal link produk dahulu.","error");$("#product-link").focus();return;}if(!existing&&(!$("#product-name").value.trim()||!$("#product-category").value.trim())){const found=await autofillProduct();if(!found){toast("Maklumat produk belum lengkap");return;}}if(!$("#product-name").value.trim()||!$("#product-category").value.trim()){setDetailsVisible(true);toast("Semak nama dan kategori produk");return;}saveButton.disabled=true;saveButton.textContent="Menyimpan...";try{let imageUrl=currentImage;if(imageMode==="upload"&&$("#product-file").files[0])imageUrl=await uploadProductImage($("#product-file").files[0],token());if(imageMode==="url")imageUrl=$("#product-image-url").value.trim();await saveProduct({id:existing?.id,name:$("#product-name").value.trim(),platform:$("#product-platform").value,category:$("#product-category").value.trim(),affiliate_url:$("#product-link").value.trim(),image_url:imageUrl,active:$("#product-active").checked,position:existing?.position||products.length+1},token());closeDrawer();await loadProducts();toast(existing?"Barang berjaya dikemas kini":"Barang berjaya ditambah");}catch(error){toast(error.message);}finally{saveButton.disabled=false;saveButton.textContent="Simpan barang";}};
$("#manager-search").oninput=renderList;document.querySelectorAll("#manager-tabs button").forEach(button=>button.onclick=()=>{filterPlatform=button.dataset.platform;document.querySelectorAll("#manager-tabs button").forEach(item=>item.classList.toggle("active",item===button));renderList();});
$("#cancel-delete").onclick=()=>{$("#confirm-modal").classList.add("hidden");pendingDelete=null;};
$("#confirm-delete").onclick=async()=>{if(!pendingDelete)return;try{await deleteProduct(pendingDelete.id,token());$("#confirm-modal").classList.add("hidden");pendingDelete=null;await loadProducts();toast("Barang sudah dibuang");}catch(error){toast(error.message);}};
